//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromotionApp.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionMaster
    {
        public long Id { get; set; }
        public long ProductId { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> ProductPrize { get; set; }
        public Nullable<decimal> PromotionPrize { get; set; }
    
        public virtual ProductMaster ProductMaster { get; set; }
    }
}
